version: "3.9"

services:
  db:
    image: ${POSTGRES_TAG}
    
    volumes:
      - PGDATA:/var/lib/postgresql/data
    networks:
      webnet:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1g
      restart_policy:
        condition: on-failure
  studio:
    image: studio:${IMAGE_TAG}    
    networks:
      webnet:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      replicas: 1
      resources:
        limits:         
          memory: 250m
      restart_policy:
        condition: on-failure
  app:
    image: faw:${IMAGE_TAG}    
    environment:
     # google credentials
       GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
       FIREBASE_API_KEY: ${FIREBASE_API_KEY}
       STORAGE_BUCKET: ${STORAGE_BUCKET}
       FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      #sendgrid email
       SENDGRID_API_KEY: ${SENDGRID_API_KEY}
       SENDGRID_SENDER_EMAIL: ${SENDGRID_SENDER_EMAIL}
       SENDGRID_ACCOUNT_ACTIVATION_TEMPLATE: ${SENDGRID_ACCOUNT_ACTIVATION_TEMPLATE}
       SENDGRID_ACCOUNT_DEACTIVATION_TEMPLATE: ${SENDGRID_ACCOUNT_DEACTIVATION_TEMPLATE}
       SENDGRID_WELCOME_TEMPLATE: ${SENDGRID_WELCOME_TEMPLATE}
       DATABASE_URL: ${DATABASE_URL}
      
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${PWD}/${GOOGLE_APPLICATION_CREDENTIALS}:/usr/src/app/${GOOGLE_APPLICATION_CREDENTIALS}
      - ./webserver/web-root/public:/usr/src/app/dist/public
    networks:
      webnet:

    deploy:
      replicas: 2
      # resources:
      #   limits:
      #     cpus: "1"
      #     memory: 1g
      restart_policy:
        condition: on-failure
  
  webserver:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
      # - published: 5555
      #   target: 5555
    volumes:
      - ./webserver/web-root/public:/var/www/html
      - ./webserver/nginx-conf:/etc/nginx/conf.d
      - ./webserver/certbot/certbot-etc:/etc/letsencrypt
      - ./webserver/certbot/certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    networks:
      webnet:
    deploy:
      replicas: 1
      # resources:
      #  limits:
      #    cpus: "1"
      #    memory: 1g
      restart_policy:
        condition: on-failure
        
networks:
  webnet:
volumes:
  PGDATA:

